/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ExpensesLazyImport = createFileRoute('/expenses')()
const CreateExpenseLazyImport = createFileRoute('/create-expense')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ExpensesLazyRoute = ExpensesLazyImport.update({
  path: '/expenses',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/expenses.lazy').then((d) => d.Route))

const CreateExpenseLazyRoute = CreateExpenseLazyImport.update({
  path: '/create-expense',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create-expense.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/create-expense': {
      id: '/create-expense'
      path: '/create-expense'
      fullPath: '/create-expense'
      preLoaderRoute: typeof CreateExpenseLazyImport
      parentRoute: typeof rootRoute
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CreateExpenseLazyRoute,
  ExpensesLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-expense",
        "/expenses"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/create-expense": {
      "filePath": "create-expense.lazy.tsx"
    },
    "/expenses": {
      "filePath": "expenses.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
